Added support for Minecraft 1.20
crpmax/mc-bots pull request #71
Opened 2023-08-01 17:28 UTC by ShayanGsh

Upgraded MCProtocolLib version.

2023-08-08 11:17 UTC, Norbiros requested changes
Can you also update `README.md`?

2023-08-09 18:03 UTC, ShayanGsh commented
I updated the version in readme and also the build version in gradle

2023-08-09 18:07 UTC, Norbiros approved these changes
LGTM!

2023-08-11 10:39 UTC, bananasmoothii commented
I got this issue for one bot among 10 with [ShayanGsh's fork](https://github.com/ShayanGsh/mc-bots):
```
[12:30:17] INFO | dRpkX6IR7KbuW1dy disconnected
[12:30:17] INFO |  -> java.lang.ClassCastException: class net.kyori.adventure.text.format.TextColorImpl cannot be cast to class net.kyori.adventure.text.format.NamedTextColor (net.kyori.adventure.text.format.TextColorImpl and net.kyori.adventure.text.format.NamedTextColor are in unnamed module of loader 'app')
ALL> java.lang.ClassCastException: class net.kyori.adventure.text.format.TextColorImpl cannot be cast to class net.kyori.adventure.text.format.NamedTextColor (net.kyori.adventure.text.format.TextColorImpl and net.kyori.adventure.text.format.NamedTextColor are in unnamed module of loader 'app')
        at me.creepermaxcz.mcbots.Utils.getFullText(Utils.java:45)
        at me.creepermaxcz.mcbots.Utils.getFullText(Utils.java:33)
        at me.creepermaxcz.mcbots.MainListener.packetReceived(MainListener.java:48)
        at com.github.steveice10.packetlib.tcp.TcpSession.callPacketReceived(TcpSession.java:157)
        at com.github.steveice10.packetlib.tcp.TcpSession.lambda$channelRead0$2(TcpSession.java:386)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1589)
```
When sending the message (formatted with [MiniMessages](https://docs.advntr.dev/minimessage/index.html)): `<#2FAFEE><b>Event<dark_gray>: </dark_gray><white>The event has begun.</white></b> Good luck, <player_name>!`

2023-08-11 12:36 UTC, Norbiros commented
Can you reproduce this problem while using 1.19.4 version od mc-bots?

2023-08-12 14:38 UTC, bananasmoothii commented
I will do this in about 10 days, feel free to ping me if I forget

2023-08-14 20:46 UTC, merged